### ISSUE TITLE
NixOs on Mac M1 got confused between /lib and /lib64

### ISSUE THREAD

**Issue by tobiasBora** [Mic92/nix-ld#27]
As I was trying to help someone [here](https://discourse.nixos.org/t/cant-patch-binary-with-nix-ld-could-not-open-lib64-ld-linux-x86-64-so-2/21383/2) to use nix-ld, it seems that on the Mac M1 hardware nix-ld creates a `/lib` folder while softwares try to launch softwares in `/lib64`. So I guess that the Mac architecture should be added to the list in https://github.com/Mic92/nix-ld/blob/c25cc4b5ec65f03c2bb96f927ae724a59c51d7ee/nix-ld.nix But as I'm not an expert I may misunderstood something.

**Comment by tobiasBora** [comment]
And I'm also curious: if I have a 64 bits computer but want to run 32 bits binaries, shouldn't we also populate the folder `/lib` even on 64 bits hardwares?

**Comment by tobiasBora** [comment]
Ok, seems like M1 it actually an arm plateform so the problem comes from the package that tried to be run. That said I'm still interested to know more about how I could run 32 bits software on a 64 bits plateform.

**Comment by Mic92** [comment]
Some processors allow 32-bit ARM code in 64-bit operating systems. Not sure if this is the case for M1.

**Comment by tobiasBora** [comment]
On intel (x86_64) it is the case that 32 bit applications can run on 64 bit softwares, right? Should we create therefore an appropriate loader for this case as well? Should I open another issue?

**Comment by Mic92** [comment]
nix-ld should already operate. It's just the nixos module that would need to be symlinked to the path where 32-bit glibc-based applications expect it.

**Comment by tobiasBora** [comment]
Thanks. When you say that nix-ld should already operate you mean that the binary should work but that the module should still be modified to point to it? I created a new issue for this problem https://github.com/Mic92/nix-ld/issues/28
