### ISSUE TITLE
Enable nix-ld system-wide and include all system packages

### ISSUE THREAD

**Issue by VanCoding** [Mic92/nix-ld#30]
Is there a recommended way to enable nix-ld system-wide on NixOS and include all specifyied systemPackages (and also ones that are added through other options, like libGL etc.)?

This would make running unpatched binaries much easier I think.

**Comment by Mic92** [comment]
Have a look at this: https://github.com/Mic92/nix-ld/pull/31/files

**Comment by Quoteme** [comment]
@Mic92 Having these options would be amazing!
Could you add this to [nixpkgs](https://github.com/NixOS/nixpkgs/blob/nixos-22.11/nixos/modules/programs/nix-ld.nix) as well?

**Comment by Mic92** [comment]
That's the plan
