### ISSUE TITLE
sigsegv trying to start remote IDE session via JetBrains Gateway

### ISSUE THREAD

**Issue by pschyska** [Mic92/nix-ld#40]
When trying to start a remote IDE session via JetBrains Gateway on a nix-ld enabled host, java crash-loops with SEGV:

```
# coredumpctl info
           PID: 205075 (ld-linux-x86-64)
           UID: 1000 (…)
           GID: 100 (users)
        Signal: 11 (SEGV)
     Timestamp: Tue 2023-01-17 12:16:55 CET (3min 3s ago)
  Command Line: /lib64/ld-linux-x86-64.so.2 --library-path /home/…/.cache/JetBrains/RemoteDev/dist/1e90e5f5fc61f_CLion-2022.3.1/plugins/remote-dev-server/selfcontained/lib /home/…/.cache/JetBrains/RemoteDev-CL/…/pid.204940.temp.jbr/bin/java.bin …
    Executable: /nix/store/pm0ihc6sl28ishcz6w8gxfxg4f6rzj8r-nix-ld-1.0.3/libexec/nix-ld
 Control Group: /user.slice/user-1000.slice/session-3.scope
          Unit: session-3.scope
         Slice: user-1000.slice
       Session: 3
     Owner UID: 1000 (…)
       Boot ID: …
    Machine ID: …
      Hostname: …
       Storage: /var/lib/systemd/coredump/core.ld-linux-x86-64.….zst (present)
  Size on Disk: 12.9K
       Message: Process 205075 (ld-linux-x86-64) of user 1000 dumped core.

                Module /nix/store/pm0ihc6sl28ishcz6w8gxfxg4f6rzj8r-nix-ld-1.0.3/libexec/nix-ld without build-id.
                Stack trace of thread 205075:
                #0  0x00007f1a213d3b60 _dl_process_pt_gnu_property (/nix/store/ayfr5l52xkqqjn3n4h9jfacgnchz1z7s-glibc-2.35-224/lib/ld-linux-x86-64.so.2 + 0x7b60)
                #1  0x00007f1a213eb457 dl_main (/nix/store/ayfr5l52xkqqjn3n4h9jfacgnchz1z7s-glibc-2.35-224/lib/ld-linux-x86-64.so.2 + 0x1f457)
                #2  0x00007f1a213e8a06 _dl_sysdep_start (/nix/store/ayfr5l52xkqqjn3n4h9jfacgnchz1z7s-glibc-2.35-224/lib/ld-linux-x86-64.so.2 + 0x1ca06)
                #3  0x00007f1a213ea5ad _dl_start (/nix/store/ayfr5l52xkqqjn3n4h9jfacgnchz1z7s-glibc-2.35-224/lib/ld-linux-x86-64.so.2 + 0x1e5ad)
                #4  0x00007f1a213e93a8 _start (/nix/store/ayfr5l52xkqqjn3n4h9jfacgnchz1z7s-glibc-2.35-224/lib/ld-linux-x86-64.so.2 + 0x1d3a8)
                ELF object binary architecture: AMD x86-64

```

I was unable to debug with gdb due to missing debuginfo. Do you happen to know how to override `/lib64/ld-linux-x86-64.so.2` with debuginfo, without having to override glibc globally, which would trigger a full system rebuild?

**Comment by SuperSandro2000** [comment]
You could use ``system.replaceRuntimeDependencies`` to only replace the final package.
Do you know the command that is being executed? Can you run strace on it?

**Comment by Mic92** [comment]
You wouldn't override `/lib64/ld-linux-x86-64.so.2` because this is not your libc. Instead, you would set NIX_LD to a glibc with debug symbols.

**Comment by Mic92** [comment]
The crash also happens actually in glibc and not in nix-ld as you can see from the stacktrace.

**Comment by Mic92** [comment]
I have not added yet support to make `nix-ld` an executable - it's only a library, so the way you are trying to start will not work  yet.

**Comment by pschyska** [comment]
> I have not added yet support to make `nix-ld` an executable - it's only a library, so the way you are trying to start will not work yet. For now you have to manually replace `/lib64/ld-linux-x86-64.so.2` in your script with the actual glibc link loader.

Ah yes! This is it. I didn't realize the script [^1] actually calls `ld-linux-x86-64.so.2 --library-path … exe` instead of `LD_LIBRARY_PATH=… exe`. I'll try to find out if that behaviour can be controlled somehow. I think I should be able to hack $PATH for this specific use-case to prefer glibc instead of nix-ld.

Would it be hard to make nix-ld executable standalone by putting the arguments into `(NIX_?)LD_LIBRARY_PATH` and calling into glibc? Or alternatively (as nix-ld's functionality is not required here) just forwarding to `${glibc}/…/ld-linux-x86-64.so.2`?


[^1]: Which unfortunately isn't mine, but JetBrains'. AFAICS an attempt to be able to deploy IDEs to arbitary "linux" hosts over ssh without incurring remote dependencies by shipping some .so files with it  — which faceplants on systems like NixOS. To add insult to injury it all happens in some temporary folders which disappear after the processes crash, but I'll try to preserve them somehow, or find the source of this script.

**Comment by Mic92** [comment]
Not so hard, it would be another `execeve` to $NIX_LD, if it detects that it is not called as a library.

**Comment by Mic92** [comment]
so musl libc detect this by checking if `aux[AT_BASE]` is set:

https://git.musl-libc.org/cgit/musl/tree/ldso/dlstart.c?id=f47a8cdd250d9163fcfb39bf4e9d813957c0b187#n104

**Comment by Mic92** [comment]
fixed in https://github.com/Mic92/nix-ld/pull/47
