### ISSUE TITLE
Docker image support

### ISSUE THREAD

**Issue by Atry** [Mic92/nix-ld#50]
According to https://github.com/Mic92/nix-ld#does-this-work-on-non-nixos-system, `nix-ld` does not support non-NixOS systems.

I wonder if it is possible to add `nix-ld`'s `ld-linux-x86-64.so.2` to a Docker image that does not include neither NixOS nor other Linux distribution, i.e. built from `pkgs.dockerTools.buildLayeredImage`, which is not a NixOS because most container runtimes do not support `systemd` and `tmpfiles.d`.

**Comment by Mic92** [comment]
Yes. That work. tmpfiles.d is not really required you can also just do a symbolic link:

```
ls -la /lib64/ld-linux-x86-64.so.2
lrwxrwxrwx root root 71 B 3 days ago  /lib64/ld-linux-x86-64.so.2@ ⇒ /nix/store/kg2wi9jvg03si4gxjp1l60qj4w9giqjp-nix-ld-1.0.3/libexec/nix-ld
```

**Comment by Atry** [comment]
> you can also directly symlink glibc from to /lib64/ld-linux-x86-64.so.2 and than LD_LIBRARY_PATH instead

Sorry. What does that mean?

**Comment by Mic92** [comment]
The point of nix-ld is that in a normal environment you don't want to set LD_LIBRARY_PATH because it might interfere with other applications. However if you have a special purpose application container than it might be easier to set LD_LIBRARY_PATH directly instead of NIX_LD_LIBRARY_PATH and symlink /lib64/ld-linux-x86-64.so.2 to "${glibc}/lib/ld-linux-x86-64.so.2"

**Comment by wokalski** [comment]
For future reference; to make it work in docker images do the following:

1. Add `pkgs.nix-ld` to your docker image
2. Set Env in the image like so:
```
"NIX_LD_LIBRARY_PATH=${pkgs.lib.makeLibraryPath [ pkgs.stdenv.cc ]}"
''NIX_LD=${pkgs.lib.fileContents "${pkgs.stdenv.cc}/nix-support/dynamic-linker"}''
```
3. 
```
runAsRoot = ''
  mkdir /lib64
  ln -s /libexec/nix-ld /lib64/$(basename  $(< ${pkgs.stdenv.cc}/nix-support/dynamic-linker))
'';
```

**Comment by Mic92** [comment]
Feel free to add a wiki page about this: https://github.com/Mic92/nix-ld/wiki

**Comment by wokalski** [comment]
The wiki doesn't exist 😄 (or at least I cannot access it)

**Comment by Mic92** [comment]
Can you not edit anything in there? https://github.com/Mic92/nix-ld/wiki

**Comment by Mic92** [comment]
I just removed the `Restrict editing to collaborators only` option.
