### ISSUE TITLE
Possible to enable nix-ld on a per-project basis?

### ISSUE THREAD

**Issue by bonsairobo** [Mic92/nix-ld#61]
I'm considering replacing my current usage of `buildFHSEnv` with `nix-ld`, but this would come with a UX tradeoff. Users of `nix-ld` must install it system-wide (please correct me if that's wrong) before it can be used in a `shell.nix` or `flake.nix` of a specific project. This makes it harder to isolate the dependency on `nix-ld`, as all collaborators (on NixOS) on a project would need to install `nix-ld` before they can `nix-shell` or `nix develop`.

Is it feasible to install `nix-ld` on a per-project basis like `buildFHSEnv` can?

**Comment by Mic92** [comment]
If you are doing `buildFHSEnv`, you are already getting `/lib64/ld-linux-x86-64.so.2` based on the real glibc and you don't need nix-ld in the first place. So it doesn't make sense to replicate this behavior with `nix-ld`. I would say `buildFHSEnv` is the per project-based alternative to `nix-ld`.

**Comment by bonsairobo** [comment]
> it doesn't make sense to replicate this behavior with nix-ld

`buildFHSEnv` does quite a bit more than just providing a global loader. It simulates an entire file hierarchy for binaries and libraries in the nix store. And as it's said in the README of `nix-ld`:

> these sandboxes have their own weaknesses:
>
>  - setuid binaries cannot be executed inside a fhsuserenv
>  - inside a buildFHSUserEnv you can not use other sandbox tools like bwrap or 'nix build'.
>  - buildFHSUserEnv requires a subshell which does not work well with direnv

I couldn't say if any of these weaknesses are strictly a result of the per-project nature of `buildFHSEnv`, so I ask you to consider that.

So it would seem there is room for a per-project `nix-ld` to overcome the weaknesses of `buildFHSEnv`.

**Comment by Mic92** [comment]
You can enable NIX_LD_LIBRARY_PATH in your project's devshell. Is this what you want?

**Comment by bonsairobo** [comment]
> You can enable NIX_LD_LIBRARY_PATH in your project's devshell. Is this not what you want?

For this to have any effect, doesn't that require that `nix-ld` is already installed on your system?

**Comment by Mic92** [comment]
> > You can enable NIX_LD_LIBRARY_PATH in your project's devshell. Is this not what you want?
> 
> For this to have any effect, doesn't that require that `nix-ld` is already installed on your system?

Yes. But it needs to be. This is the tradeoff. I don't see how otherwise nix-ld would be made work.

**Comment by rupurt** [comment]
Would definitely love to figure out how to make this work on per project basis. For example I personally use `home-manager`. But most people on my team don't, and they don't want to do it either which I feel like is completely understandable.
