### ISSUE TITLE
Discussion: An Idea for fixing the child inheritance problem

### ISSUE THREAD

**Issue by jeff-hykin** [Mic92/nix-ld#69]
This isn't a feature request; I'm considering working on the problem myself in a different tool. I just want to make sure I'm not trying something that definitely won't work.

I know mutation is a bad idea, but let's ignore just that one aspect for now.

_

Let's say a binary runs, and calls nix-ld. 

If there's no way to know what binary is calling nix-ld then this idea is dead in the water. But I'm hoping there's some way, maybe via strace or some similar tool if there's no direct way to know.

If that's the case, I imagine nix-ld could predict the absolute path of each of the .so files the target binary was looking for (using nix ld env var).

In that case, could it mutate the RPATH (not RUNPATH) of the binary at runtime? And then simply not change any env vars for the binary.

If it wouldn't work at runtime, do you think it could it work on the second run? (fall on the first call, then patch, then call again)

_

Back to the mutation problem; if there is a test suite for a tool, and we are running the test suite over and over again inside of a nix build, even if the binary is mutating if it's stable by the end of the test suit calls then the final build of a nix tool with a lot of outside binaries could still lead to a consistent output.

**Comment by Mic92** [comment]
So do you want to know what process called `execv` or do you want to know what program is currently started with nix-ld as the interpreter?

**Comment by jeff-hykin** [comment]
Hmm, I was assuming those would be the same process at different phases of execution. Which may show that I don't know enough.

If I had to pick, I'm guessing it would be more helpful to know what currently started with nix-ld as the interpreter

**Comment by Mic92** [comment]
There is a data structure called auxv that linux passes the link-loader (aka elf interpreter).
It contains a field called `AT_EXECFD` that has the file descriptor of the original file that was executed. You can read about auxv in this article: https://fasterthanli.me/series/making-our-own-executable-packer/part-16
